sudo: false

language: erlang

before_install:
  - pip install --user cpp-coveralls coveralls-merge

install:
  - rebar get-deps

script: rebar compile xref && rebar skip_deps=true eunit

otp_release:
  - 19.3
  - 22.2

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp' --dump c.json
  - coveralls-merge c.json erlang.json
