name: CI

on: [push, pull_request]

jobs:

  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        otp: ['19.3', 24]
    runs-on: ubuntu-20.04
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v2
    - run: rebar3 compile
      #- run: rebar3 xref
      #- run: rebar3 dialyzer
    - run: rebar3 edoc

    - name: Run tests
      if: matrix.otp != 24
      run: rebar3 eunit -v
    - name: Run tests (OTP 24)
      if: matrix.otp == 24
      id: ctstep
      run: rebar3 eunit -v

    - name: result1
      run: |
        echo 'Resultado1: steps.ctstep.outcome'
      continue-on-error: true

    - name: result2
      run: |
        echo 'Resultado2: ${{ steps.ctstep.outcome }}'
      continue-on-error: true

    - name: Upload edoc to GitHub Pages
      if: (steps.ctstep.outcome == 'failure') && (github.repository == 'badlop/cache_tab')
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: doc
        destination_dir: edoc
        publish_branch: ecil
        keep_files: true

    - name: View links to Github Pages
      if: (steps.ctstep.outcome != 'success') && (github.repository == 'badlop/cache_tab')
      run: |
        echo "::notice::View this EDoc: https://badlop.github.io/cache_tab/"
