name: CI

on: [push, pull_request]

jobs:

  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        otp: ['19.3', 24]
    runs-on: ubuntu-20.04
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v2
    - run: rebar3 compile
      #- run: rebar3 xref
    - run: |
        mkdir dialyzer
        echo "" > dialyzer/error.log
      if: matrix.otp != 24
    - run: rebar3 dialyzer
      if: matrix.otp == 24
    - run: |
        [ ${{ matrix.otp }} = 24 ] && true || { cat dialyzer/error.log ; test ! -s dialyzer/error.log ; }
