name: Hex

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Setup rebar3 hex
        run: |
          mkdir -p ~/.config/rebar3/
          echo "{plugins, [rebar3_hex]}." > ~/.config/rebar3/rebar.config

      - run: mkdir docs

      - uses: ZacJW/markdown-html-action@1.1.0
        with:
          input_files: '[["README.md"]]'
          output_files: '["docs/index.html"]'
          builtin_stylesheet: 'style.css'
          packages: 'pymdown-extensions'
          extensions: '["pymdownx.extra"]'

      - name: Publish to hex.pm
        run: DIAGNOSTIC=1 rebar3 hex publish --repo hexpm --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

      - name: Publish docs to hex.pm
        run: DIAGNOSTIC=1 rebar3 hex docs --repo hexpm --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

      - name: Check crash dump
        run: head rebar3.crashdump
